name: inflation-app
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - django
  - psycopg2  # PostgreSQL database adapter
  - gunicorn  # WSGI HTTP server for production
  - requests  # HTTP library for making HTTP requests
  - celery  # Distributed task queue
  - redis-py  # Redis client for Python
